spring:
  application:
    name: gateway

server:
  port: 8080
  
zuul:
  prefix: /api
  routes:
    login-service:
      path: /login-service/**
      serviceId: LOGIN-SERVICE
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8082}/eureka/
    register-with-eureka: true
